# Generated by Django 5.0.2 on 2024-02-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='mavsum',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
