# Generated by Django 5.0.2 on 2024-02-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0002_transfer_mavsum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davlat',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
